### PR TITLE
Add How-To train and deploy NN 

### PR DESCRIPTION
**Pull request by gteti**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gteti** [comment]
This should fix #82

**Review by gmacario — CHANGES_REQUESTED** [review]
We should also link the page from docs/index.rst.

I will take care of it before merging the PR

**Comment by gmacario** [comment]
@gteti do you have any screenshots to share to show the results of the commands you documented in the HOWTO?

**Review by gmacario — APPROVED** [review]

**Comment by gteti** [comment]
> @gteti do you have any screenshots to share to show the results of the commands you documented in the HOWTO?
> 
> Anyway you can simply add them in a future PR.
> 
> Looks (very) Good To Me, merging PR

The output is already displayed in the notebook. Before running each row of code, there is the output already saved.

**Comment by gmacario** [comment]
> The output is already displayed in the notebook. Before running each row of code, there is the output already saved.

I understand. But I was looking at the rendering of page https://arneis.readthedocs.io/en/latest/howto/howto-train-deploy-NN.html and believe an illustration at the end of the document would help a lot.

Would you mind taking a snip of your running notebook (I do not yet have one running on my laptop as I write) and create a new PR including it in an image tag of the markdown?

**Comment by gteti** [comment]
We will talk about this on monday. There are a tons of cells to take output from that's why I said there is already the potential output in the source notebook.

**Comment by gteti** [comment]
Is this good enough ? 
image

**Pull request merged**
