### PR TITLE
Feat/publish moc on docs

### LINKED ISSUE #140: [FEAT]: Assemble the ARNEIS conveyor with physical LEGO blocks
### Description

Assemble the ARNEIS conveyor based on the current design ([bottle-conveyor-20220206.io](https://github.com/B-AROL-O/ARNEIS/blob/main/mocs/studies/bottle-conveyor-20220206.io)) published under [mocs/studies](https://github.com/B-AROL-O/ARNEIS/tree/main/mocs/studies)

Prerequisite: Issue #7 resolved

### Additional Information

Deliverables:

* Physical assembly
* Some photos and/or videos to document the process and especially the outcome
* Any issues encountered filed as bugs on the design

### PR DESCRIPTION
**Pull request by alv67**
Closes #140  

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
@alv67 I did not merge this PR in dev-cw07 since it was not passing tests, sorry...

**Comment by alv67** [comment]
Need to exclude check for two md files… these files does not have Title but only include so they do not pass the linter
Il 20 feb 2022, 21:54 +0100, Gianpaolo Macario ***@***.***>, ha scritto:

**Comment by gmacario** [comment]
> Need to exclude check for two md files…

Donw

**Comment by gteti** [comment]
You have already merged this
```bash
[.github/linters/.markdown-lint.yml](https://github.com/B-AROL-O/ARNEIS/pull/185/files/775295f828d9dd2e7d5dd3526a327c60a95e135f..714d4cdc03c12178e0bfae80f865a0f3d94717e9#diff-2fd3619d2b7372123257bc21645edb90c24293e66babbc6053033a89e21bab34)[](https://github.com/B-AROL-O/ARNEIS/pull/185/files/775295f828d9dd2e7d5dd3526a327c60a95e135f..714d4cdc03c12178e0bfae80f865a0f3d94717e9#diff-2fd3619d2b7372123257bc21645edb90c24293e66babbc6053033a89e21bab34) 
Viewed
@@ -28,6 +28,7 @@ MD026:
MD029: false                  # Ordered list item prefix
MD033: false                  # Allow inline HTML
MD036: false                  # Emphasis used instead of a heading
MD041: false                  # First line in a file should be a top-level heading
```

Making it work for ALL the repository content. I think it would have been better to disable the rule just for the single files .md and not for ALL the repository.

**Comment by gmacario** [comment]
Good point @gteti.
Would you like to try and improve the code with the PR as you suggested?

**Comment by gteti** [comment]
> Good point @gteti.
> 
> Would you like to try and improve the code with the PR as you suggested?
> 
> Otherwise just create a Bug and assign it to me so I will not forget. Thanks!

See #189

**Pull request merged**
