### PR TITLE
[FIX]: Extend copyright of ARNEIS project to 2024

### LINKED ISSUE #374: [FEAT]: Extend copyright to 2024
### Description

On both the toplevel README.md as well as the generated website (https://arneis.readthedocs.io)

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by gmacario**
## 📑 Description

Closes #374

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
@alv67 and @gteti hopefully I should have fixed all occurrencies.
Please double check and merge if LGTY as well.

**Review by alv67 — APPROVED** [review]
Two more files edited

**Comment by gmacario** [comment]
> Two more files edited

Thanks @alv67 for your sharp eyes 😄 

Merging PR.

**Comment by alv67** [comment]
The github search tool is useful. There is another copyright in my python script but I decided that 2022 was right for that file.

**Pull request merged**
