### PR TITLE
[FEAT]: Add CI workflow to check for commonly misspelled words

### PR DESCRIPTION
**Pull request by gmacario**
## 📑 Description

On every push, pull request, and periodically, use codespell to check for commonly misspelled words.

In the event of a false positive, the problematic word should be added, in all lowercase, to the field of . Regardless of the case of the word in the false positive, it must be in all lowercase in the ignore list. The ignore list is comma-separated with no spaces.

Based upon https://github.com/arduino/meta-partner-arduino/tree/main/.github/workflows

See https://github.com/arduino/meta-partner-arduino/pull/26

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
It looks like the remaining errors reported by spellcheck are true positives.

Excerpt from https://github.com/B-AROL-O/ARNEIS/actions/runs/7612599207/job/20730560239?pr=376

```text
Running codespell on '' with the following options...
Check filenames? ''
Check hidden? ''
Exclude file ''
Skipping './.git'
Builtin dictionaries ''
Ignore words file ''
Ignore words list ''
Ignore URI words list ''
Resulting CLI options  --skip ./.git
Error: ./mocs/studies/README.md:12: avalaible ==> available
Error: ./mocs/studies/camera-support/README.md:3: Technics ==> Techniques
25
Error: ./mocs/project/README.md:12: avalaible ==> available
Error: ./code/poweredupapp-flash-move/README.md:10: Technics ==> Techniques
Error: ./docs/bibliography.md:37: Technics ==> Techniques
Error: ./docs/bibliography.md:47: Technics ==> Techniques
Error: ./docs/arneis-social-media.md:[6](https://github.com/B-AROL-O/ARNEIS/actions/runs/7612599207/job/20730560239?pr=376#step:4:7)[7](https://github.com/B-AROL-O/ARNEIS/actions/runs/7612599207/job/20730560239?pr=376#step:4:8): Technics ==> Techniques
Error: ./docs/howto/howto-install-raspios64.md:153: usin ==> using
Error: ./docs/howto/howto-install-raspios64.md:192: passowrd ==> password
Error: ./docs/howto/howto-prepare-rpi4b-for-arneis.md:77: usin ==> using
Error: ./docs/howto/howto-prepare-rpi4b-for-arneis.md:116: passowrd ==> password
Error: ./docs/howto/howto-use-rclone-with-cubbit-ds3.md:327: compre ==> compare, compère
Error: ./docs/howto/howto-install-k3s-for-arneis.md:927: Uniqu ==> Unique
Error: ./docs/howto/howto-install-micropython-nano33ble.md:63: modifiying ==> modifying
Error: ./docs/howto/howto-install-depthai-on-rpi.md:[8](https://github.com/B-AROL-O/ARNEIS/actions/runs/7612599207/job/20730560239?pr=376#step:4:9)3: displyed ==> displayed
Error: ./docs/howto/howto-control-rpi-poweredup.md:74: succesful ==> successful
Error: ./docs/howto/howto-control-rpi-poweredup.md:[9](https://github.com/B-AROL-O/ARNEIS/actions/runs/7612599207/job/20730560239?pr=376#step:4:10)8: Technics ==> Techniques
Error: ./docs/howto/howto-control-rpi-poweredup.md:206: Technics ==> Techniques
Error: ./docs/howto/howto-control-rpi-poweredup.md:2[16](https://github.com/B-AROL-O/ARNEIS/actions/runs/7612599207/job/20730560239?pr=376#step:4:17): Technics ==> Techniques
Error: ./docs/howto/howto-control-rpi-poweredup.md:224: Technics ==> Techniques
Error: ./docs/howto/howto-configure-google-analytics.md:5: followint ==> following
Error: ./docs/howto/howto-configure-google-analytics.md:32: visualisations ==> visualizations
Error: ./docs/howto/howto-train-deploy-NN.md:55: adviced ==> advised
Error: ./docs/howto/howto-train-deploy-NN.md:76: cointains ==> contains
Error: ./docs/architecture/arneis-swarch.md:46: Technics ==> Techniques
Codespell found one or more problems
```

CC: @alv67, @gteti

**Comment by alv67** [comment]
Mine only typo is "avalaible" all other are from @gmacario and @gteti .
Since I'm a good boy I fixed some of yours too.
All "Technics" are not typos, I tried to disable that with different editing on spell-check.yml configuration.

 @gmacario is up to you fix the :
```
Error: ./docs/howto/howto-use-rclone-with-cubbit-ds3.md:327: compre ==> compare, compère
Error: ./docs/howto/howto-install-k3s-for-arneis.md:927: Uniqu ==> Unique
```
those are not typos, please check by yourself.

**Comment by gmacario** [comment]
Thanks @alv67 for your contribution.

> Mine only typo is "avalaible" all other are from @gmacario and @gteti .
> Since I'm a good boy I fixed some of yours too.
> All "Technics" are not typos,

AFAIK "Technic" is a correct word (and already whitelisted in toplevel `.codespellrc`) while "Technics" is not.
Please see <https://www.lego.com/it-it/themes/technic>

> I tried to disable that with different editing on spell-check.yml configuration.

AFAIK the config file to be used is `.codespellrc`

> @gmacario is up to you fix the :
> 
> ```
> Error: ./docs/howto/howto-use-rclone-with-cubbit-ds3.md:327: compre ==> compare, compère
> Error: ./docs/howto/howto-install-k3s-for-arneis.md:927: Uniqu ==> Unique
> ```
> 
> those are not typos, please check by yourself.

OK, will have a look

**Comment by gmacario** [comment]
Everything should be fixed now.
@alv67 please review and merge if you agree.

**Review by alv67 — APPROVED** [review]

**Pull request merged**
