### PR TITLE
Create test_multiple_OAKD.py

### PR DESCRIPTION
**Pull request by gteti**
Closes # 

## ✅ Checks

- [X] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

As shown at https://docs.luxonis.com/projects/api/en/latest/tutorials/multiple/#multiple-depthai-per-host

### CODE REVIEW

**Comment by gmacario** [comment]
@gteti For My Understanding:

- Did you write the attached `test_multiple_OAKD.py` file from scratch
- or did you leverage an existing codebase? If so, which one?

**Comment by gteti** [comment]
> @gteti For My Understanding:
> 
>     * Did you write the attached `test_multiple_OAKD.py` file from scratch
> 
>     * or did you leverage an existing codebase? If so, which one?

I wrote the code looking at the example linked in the _Additional Information_ Section.

**Comment by gmacario** [comment]
> > @gteti For My Understanding:
> > ```
> > * Did you write the attached `test_multiple_OAKD.py` file from scratch
> > 
> > * or did you leverage an existing codebase? If so, which one?
> > ```
> 
> I wrote the code looking at the example linked in the _Additional Information_ Section.

OK, so if you manage to reproduce the bug on https://github.com/luxonis/depthai-experiments/tree/master/gen2-multiple-devices
just file an issue upstream on https://github.com/luxonis/depthai-experiments/issues

**Comment by gteti** [comment]
> OK, so if you manage to reproduce the bug on https://github.com/luxonis/depthai-experiments/tree/master/gen2-multiple-devices just file an issue upstream on https://github.com/luxonis/depthai-experiments/issues

https://github.com/luxonis/depthai-experiments/issues/280

**Comment by gteti** [comment]
@gmacario now it's only missing the following error:
` 2022-01-20 18:22:59 [ERROR]   Found errors in [black] linter!
2022-01-20 18:22:59 [ERROR]   Error code: 2. Command output:
------
Usage: black [OPTIONS] SRC ...
Try 'black -h' for help.

Error: Invalid value for '--config': File '/github/workspace/.github/linters/.python-black' does not exist.
------`

**Comment by gmacario** [comment]
> @gmacario now it's only missing the following error:
> 
> ```shell
> 2022-01-20 18:22:59 [ERROR]   Error code: 2. Command output:
> ------
> Usage: black [OPTIONS] SRC ...
> Try 'black -h' for help.
> 
> Error: Invalid value for '--config': File '/github/workspace/.github/linters/.python-black' does not exist.
> ------```
> ```

Please do `git merge origin/main` and the error should go away

**Review by alv67 — APPROVED** [review]
I added myself as a reviewer so I gan give you my approvement

**Comment by gmacario** [comment]
Let's be generous and merge as-is.

We may refactor into different subfolders later after we agree on the repository structure for code

**Review by alv67 — APPROVED** [review]

**Pull request merged**
