### PR TITLE
[Feat] docs: Add howto-rpi3p-raspios64

### LINKED ISSUE #8: Try ARNEIS codebase on a 64-bit OS
Follow-up to #6

Alternatives:
* https://downloads.raspberrypi.org/raspios_arm64/images/
* [Ubuntu Desktop for Raspberry Pi](https://ubuntu.com/Raspberry-pi)
* [HypriotOS](https://blog.hypriot.com/)
* ...

### PR DESCRIPTION
**Pull request by gmacario**
Closes #8 

## 📑 Description

Add a new HOWTO documenting how to install Raspberry Pi OS 64-bit on a Raspberry Pi 3B+ or higher to be used as an Edge Controller of the ARNEIS project.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by alv67 — APPROVED** [review]
Good.

**Comment by gmacario** [comment]
Not sure why [Super-Linter spots the following errors](https://github.com/B-AROL-O/ARNEIS/runs/5761891525?check_suite_focus=true):

```text
ERROR: 2 dead links found!
[✖] https://apps.apple.com/it/app/lego-powered-up/id1367846574 → Status: 0
[✖] https://apps.apple.com/us/app/lego-technic-control/id1465808291 → Status: 429

FILE: ./docs/howto/howto-install-raspios64.md
[✖] (https://www.raspberrypi.com/software/)
```

**Comment by gmacario** [comment]
Still cannot understand why https://github.com/B-AROL-O/ARNEIS/runs/5799861762?check_suite_focus=true

image

**Comment by gmacario** [comment]
Too late for dev-cw03 merge window, let's postpone to next sprint

**Pull request merged**
