### PR TITLE
Update Sphinx configuration

### PR DESCRIPTION
**Pull request by alv67**
Inspired by https://github.com/alv67/le-guide-di-alv

Fix #73

## 📑 Description

This PR improves the layout of <https://arneis.readthedocs.io> to make it more appealing and useful.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Review by gmacario — APPROVED** [review]
LGTM, let's get this merged so we can test it online

**Comment by gmacario** [comment]
Build triggered on https://readthedocs.org/projects/arneis/builds/

**Comment by gmacario** [comment]
Build https://readthedocs.org/projects/arneis/builds/15837920/ completed

And the result is WAY better!

image

CC: @gteti

**Comment by gteti** [comment]
Thanks @alv67 😄

**Pull request merged**
