### PR TITLE
enable pdf export

### LINKED ISSUE #191: [FEAT]: arneis.readthedocs.io: Restore PDF document generation
### Description

The fix to https://github.com/B-AROL-O/ARNEIS/issues/186 introduced in PR https://github.com/B-AROL-O/ARNEIS/pull/190 had the consequence of disabling the PDF document generation of the ARNEIS RTD site.

This task has the goal of restoring the functionality without introducing further regressions.

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by alv67**
Closes #191  

## 📑 Description

Tried in my Fork, and seems that now with PDF export enabled it works. Maybe something has been corrected.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
@alv67 how can I independently test this PR without messing up with <https://arneis.readthedocs.io>?

**Review by gmacario — COMMENTED** [review]
See above

**Comment by alv67** [comment]
The only way I found is forking it and publishing on a new temporary readthedocs page.

**Comment by gmacario** [comment]
OK, let us merge it, then

**Pull request merged**
