### PR TITLE
howto: Create howto-create-landing-page-netlify.md

### LINKED ISSUE #349: [FEAT]: Create HOWTO explaining how to create a Landing Page
### Description

Create a detailed writeup walking through the steps executed to create the initial version of <https://baroloteam.online>

### Additional Information

Related to:

* https://github.com/B-AROL-O/baroloteam.online/issues/1
* https://github.com/B-AROL-O/baroloteam.online/issues/2

### PR DESCRIPTION
**Pull request by gmacario**
## 📑 Description

Add a HOWTO with a detailed walkthrough of the steps executed to create the initial version of https://baroloteam.online/

Closes #349

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [ ] All the tests have passed

### CODE REVIEW

**Comment by gmacario** [comment]
@alv67 and/or @gteti would you please give it a look and let me know if you agree to merge?

I added a new HOWTO to https://arneis.readthedocs.io/

The new page which you can preview at https://arneis--350.org.readthedocs.build/en/350/howto/howto-create-landing-page-netlify.html contains some TODO but I believe is already OK for public consumption.

**Comment by gmacario** [comment]
Ping @alv67 and/or @gteti 🙏

**Comment by gteti** [comment]
Good for me.

**Comment by gmacario** [comment]
Thanks @gteti, merging PR

**Comment by alv67** [comment]
I agree

**Pull request merged**
