### PR TITLE
New improved B-AROL-O logo, issue #35

### LINKED ISSUE #35: [FEAT]: Enhancements to B-AROL-O logo
### Description

Hi! I would like to enhance your logo since there are some details that can be improved :smile:

In these days I will provide you the results! Here what I would like to modify:

* Make the curve simmetrical on both edges
* The B should be put in the middle of the image which I've tried to understand by drawing a line in the middle of the gear. So maybe it should go like some millimeters/pixels down.
* Change the bottom layout

image

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by pitdagosti**
Closes #35 

## 📑 Description

New proposal for the B-AROL-O logo, with the modified changes mentioned in the issue mentioned above

## ℹ Additional Information

If it is approved, I will upload the plain and the B/W versions

### CODE REVIEW

**Comment by gmacario** [comment]
Thanks @pitdagosti for your contribution, LGTM.

Let's hear @alv67 and @gteti feedbacks as well so this may become the **official** B-AROL-O** logo.

However if you don't mind I recommend to put this PR on hold and merge it only after we close https://github.com/B-AROL-O/ARNEIS/issues/12 and possibly also https://github.com/B-AROL-O/ARNEIS/issues/29

In the meanwhile I do not want to stop your contribution, there are still a lot of [unassigned issues](https://github.com/B-AROL-O/ARNEIS/issues?q=is%3Aopen+is%3Aissue+no%3Aassignee) you can starting having a look at (hint: maybe https://github.com/B-AROL-O/ARNEIS/issues/24?)

**Review by gteti — APPROVED** [review]
Good for me! Thanks

**Comment by pitdagosti** [comment]
Sure! I'll check them :smile:

**Comment by gmacario** [comment]
By the way @pitdagosti I had a look at the interesting link you mentioned yesterday
https://github.com/chuckreynolds/social-profile-image-sizes

I would assume you already took those sizes into account when designing your updated logo, right?

**Comment by pitdagosti** [comment]
it's a svg file, however I can export the drawing as .png with the sizes you prefer

If you want I can create some folders with inside the different logos (shaded,plain,B/W) as png for every social media with their actual size

**Review by alv67 — APPROVED** [review]
Good work!!

**Comment by gmacario** [comment]
> it's a svg file, however I can export the drawing as .png with the sizes you prefer

Yes I agree. My question was most related to the _aspect ratio_ of the image.

Anyway the image (I mean, the non-blank part) look square and with sufficient white space around so it should easily be scaled at nearly all the sizes stated in https://github.com/chuckreynolds/social-profile-image-sizes

> If you want I can create some folders with inside the different logos (shaded,plain,B/W) as png for every social media with their actual size

As part of this PR please just add the remaining two .svg then I will merge it as-is.
We will handle the bitmap conversions in a separate PR - maybe just via a command-line script

**Review by gmacario — APPROVED** [review]

**Review by gteti — APPROVED** [review]

**Comment by gmacario** [comment]
Merged as-is.

Thanks again for your contribution.
We wish you a prompt recovery!

**Pull request merged**
