### PR TITLE
README.md: Refactor home page with new contents and structure

### PR DESCRIPTION
**Pull request by gmacario**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by pitdagosti** [comment]
Here some suggestions I found reading the doc:

* line 23:  it is not wrong "everyday job" but in my opinion "ordinary" or "daily job" would sound better. Internet suggests to use work instead of job, but i prefer the last one for its employement connotation.
* line 31: However, as the old adage says: we learned it the hard way

All the rest seems okay to me :smile:

**Review by pitdagosti — CHANGES_REQUESTED** [review]
Here some suggestions I found reading the doc:

* line 23:  it is not wrong "everyday job" but in my opinion "ordinary" or "daily job" would sound better. Internet suggests to use work instead of job, but i prefer the last one for its employement connotation.
* line 31: However, as the old adage says: we learned it the hard way

All the rest seems okay to me :smile:

**Review by alv67 — APPROVED** [review]
Read and approve. You know that I do not find typos, but my brain only get the contents. 😜

**Comment by gmacario** [comment]
> Here some suggestions I found reading the doc:
> 
> ...
> 
> All the rest seems okay to me 😄

OK, so I think that with https://github.com/B-AROL-O/ARNEIS/pull/292/commits/fe921315664d15f1e3eb3cfdf690710c73884e89 everything is ready to be merged

**Pull request merged**
