### PR TITLE
[FEAT] ARNEIS logo: Improve SVG, white variant

### PR DESCRIPTION
**Pull request by alv67**
Closes # 

## 📑 Description

PLEASE CHECK IF THOSE NEW LOGOs ARE OK WHERE USED IN ACTUAL DOCUMENTS

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Review by gmacario — CHANGES_REQUESTED** [review]
@alv67 good job for the updated SVG and PNG in color and white.

However I noticed that with this change the project homepage on GitHub renders badly if displayed on a black theme as I am currently using

**Comment by gmacario** [comment]
> @alv67 good job for the updated SVG and PNG in color and white.
> 
> However I noticed that with this change the project homepage on GitHub renders badly if displayed on a black theme as I am currently using

Here is what I mean:

image

**Comment by gmacario** [comment]
Same on Google Chrome on my Huawei Mate 10 Pro (Android 10.x)

**Comment by alv67** [comment]
Restored png with white background, and renamed transparent white and black transparent versions.

**Review by gmacario — APPROVED** [review]
It looks PERFECT now!

image


LGTM, @gteti please review and if OK merge the PR.

**Pull request merged**
