### PR TITLE
[Feat] Embed YouTube video inside ARNEIS documentation 

### PR DESCRIPTION
**Pull request by gmacario**
## 📑 Description

Embed [video of the ARNEIS conveyor](https://twitter.com/avaresi/status/1486027840533499904) on toplevel <https://arneis.readthedocs.io>

Fixup to #105 

**NOTE**: Merge this only AFTER

- [x] merging #101
- [x] merging #105 
- [x] doing a git rebase

Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

## ℹ Additional Information

See:
* https://github.com/sphinx-contrib/video
* https://gist.github.com/dbrgn/2922648

### CODE REVIEW

**Comment by gmacario** [comment]
Start embedding video in README.md with #105

**Comment by gmacario** [comment]
Not so urgent, postponing for another week

**Review by alv67 — APPROVED** [review]
In my first try I embedded the video with the Iframe on the md, but I found Github did not accept it. I'm happy to see it works on the ReadTheDocs page.

**Comment by gteti** [comment]
Thanks @gmacario 😄

**Pull request merged**
