### PR TITLE
Add blob of ARNEIS trained Neural Network

### PR DESCRIPTION
**Pull request by gteti**
Closes # 

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by gteti** [comment]
Fix #31 and #138

**Review by gmacario — APPROVED** [review]
As agreed I have renamed the main/ folder under code/ to a more appropriate name.

I have also moved the blob down its proper subfolder.

Apart from that, LGTM

**Comment by alv67** [comment]
BUG REPORT:
```
gitpod /workspace/ARNEIS/code/train-arneis-nn (gteti-release-public-blob) $ python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
gitpod /workspace/ARNEIS/code/train-arneis-nn (gteti-release-public-blob) $ 
```

**Review by alv67 — CHANGES_REQUESTED** [review]
BUG REPORT:

```
gitpod /workspace/ARNEIS/code/train-arneis-nn (gteti-release-public-blob) $ python main.py
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    import cv2
ModuleNotFoundError: No module named 'cv2'
gitpod /workspace/ARNEIS/code/train-arneis-nn (gteti-release-public-blob) $ 
```

So please add a `requirement.txt` and modify README.md with `pip install ... ` statement

**Comment by gteti** [comment]
Added requirements as requested.

**Review by alv67 — APPROVED** [review]
Approve the code.

The blob is not so good: camera recognize my monitor as a "savoia" bottle  

Schermata 2022-02-22 alle 18 16 55

**Comment by gmacario** [comment]
> Approve the code.

Merging as-is

**Pull request merged**
