### PR TITLE
[Feat] New document hierarchy

### LINKED ISSUE #134: [BUG]: Wrong document hierarchy on arneis.readthedocs.io
### Description of the bug

The levels of the documents on https://arneis.readthedocs.io/ is not correct.
The HOWTOs seem the be under the "How to get in touch" section.

### Steps To Reproduce

1. Go to <https://arneis.readthedocs.io>
2. Download latest version of the site in PDF
3. Examine page 3

### Expected result

* Latest news
  - How to get in touch
* Architecture
  - ARNEIS - Specification
  - ARNEIS - System Architecture
* HOWTOs
  - HOWTO Configure arneis.readthedocs.io
  - ...
  - HOWTO Train a NN for Object Detection...
* Indices and tables

### Actual result

image

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by alv67**
Closes #134 

## 📑 Description

Restructured the TOC in the index.rst, this can produce a better PDF.

## ✅ Checks

- [x] My pull request adheres to the code style of this project
- [x] My code requires changes to the documentation
- [x] I have updated the documentation as required
- [x] All the tests have passed

### CODE REVIEW

**Comment by alv67** [comment]
@gmacario please check all the Chapter introduction text, and propose a better version. This is introduced since in the PDF chapter without will not be well formatted.

**Comment by gmacario** [comment]
> @gmacario please check all the Chapter introduction text, and propose a better version. This is introduced since in the PDF chapter without will not be well formatted.

Thanks @alv67, I checked the preview page on https://arneis--313.org.readthedocs.build/en/313/ and it looks quite good to me.
My only concern is about the contents in section "How-to Guides" as well as in section "LEGO&reg;"

image

I wonder whether it would be possible - instead of placing all the items on the same line - list each HOWTO under a separated bulleted item, like for instance

> * **Learning AI and related tools:**
>   - [HOWTO Install DepthAI on a Raspberry Pi 4B for the ARNEIS project](https://arneis--313.org.readthedocs.build/en/313/howto/howto-install-depthai-on-rpi.html)
>   - [HOWTO Install DepthAI Demo v3.0.9 on Windows 10](https://arneis--313.org.readthedocs.build/en/313/howto/howto-install-depthai-on-windows10.html)
>   - [HOWTO Train a NN for Object Detection and create a deployable model for the OAK-D-Lite](https://arneis--313.org.readthedocs.build/en/313/howto/howto-train-deploy-NN.html)

**Review by gmacario — COMMENTED** [review]
I rephrased just one word, then have a couple of questions - please see my previous comment

**Comment by alv67** [comment]
> Second question: I understand this is nitpick, but do you think it is not avoidable to have to duplicate the list of pages (one in the bulleted list, the other in the "toc" section") in docs/index.rst?

That is the trick to force the creation of correct PDF. 
Too long to explain, I will show you if you want.

**Pull request merged**
